[book]
title = "ÐecisionToolkit"
authors = ["Dariusz Depta <depta@engos.de>"]
description = "ÐecisionToolkit Documentation"
language = "en"
src = "src"

[rust]
edition = "2024"

[output.html.fold]
enable = true
level = 0

[preprocessor.yapp]
